name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Updated Node.js version

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: elijahmondero/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: elijahmondero

    - name: Build the project
      run: npm run build
      working-directory: elijahmondero

    - name: Export the project
      run: npm run export
      working-directory: elijahmondero

    - name: Configure Git
      run: |
        git config --global user.name "Elijah Mondero"
        git config --global user.email "elijahmondero@gmail.com"
      working-directory: elijahmondero

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy
      working-directory: elijahmondero

    - name: Clean up the cache (optional)
      run: rm -rf node_modules
      working-directory: elijahmondero