name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: elijahmondero

    - name: Build the project
      run: npm run build
      working-directory: elijahmondero

    # Add git user config here
    - name: Configure Git
      run: |
        git config --global user.name "Elijah Mondero"
        git config --global user.email "elijahmondero@gmail.com"
      working-directory: elijahmondero

    - name: Deploy to GitHub Pages
      run: npm run deploy
      working-directory: elijahmondero

    - name: Clean up the cache (optional)
      run: rm -rf node_modules
      working-directory: elijahmondero
